# Generated by Django 4.2 on 2023-06-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0009_category_alter_produkitem_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
